DEFAULT_MODBUS_TCP_PORT = 502
DEFAULT_UNIT_ID = 1
MODBUS_TCP_PROTOCOL_ID = 0
MBAP_HEADER_LENGTH = 7

READ_COILS = 0x01
READ_DISCRETE_INPUTS = 0x02
READ_HOLDING_REGISTERS = 0x03
READ_INPUT_REGISTERS = 0x04
WRITE_SINGLE_COIL = 0x05
WRITE_SINGLE_REGISTER = 0x06
WRITE_MULTIPLE_COILS = 0x0F
WRITE_MULTIPLE_REGISTERS = 0x10
READ_WRITE_MULTIPLE_REGISTERS = 0x17

ILLEGAL_FUNCTION = 0x01
ILLEGAL_DATA_ADDRESS = 0x02
ILLEGAL_DATA_VALUE = 0x03
SERVER_DEVICE_FAILURE = 0x04
